### ISSUE TITLE
EVG parameter erro

### ISSUE THREAD

**Issue by unavailable-2374** [JiaoLab2021/EVG#4]
**1. What were you trying to do?**
genotype

**2. What did you want to happen?**
get a VCF file

**3. What actually happened?**
some err occured

**4. What data and command can the EVG dev team use to make the problem happen?**
this is my command: EVG -r ../../ref.fa -v 1.cooked.vcf.gz -s sample.txt --restart

**5. What does running `EVG` say?**

```
[2024-04-13 10:50:14,591] CMD: /public/tools/EVG/graphvcf convert -r /public/genome/output/VCF/convert/convert.ref.fa -v /public/genome/output/VCF/1.cooked.vcf.gz -l 350 -o convert.1.cooked.vcf
[2024-04-13 10:50:59,202] CMD: bgzip -@ 10 -f  && tabix -f .gz
Traceback (most recent call last):
  File "/public/tools/EVG/EVG", line 750, in <module>
    main()
  File "/public/tools/EVG/EVG", line 738, in main
    EVGClass.file_convert_index()
  File "/public/tools/EVG/EVG", line 454, in file_convert_index
    self.execute_and_check(self.vcf_convert, convert_dir)
  File "/public/tools/EVG/EVG", line 129, in execute_and_check
    stdout, stderr, log_out = function(*args)
  File "/public/tools/EVG/EVG", line 254, in vcf_convert
    stdout, stderr, log_out, sv_file_gz = convert.bgzip_vcf(sv_file, self.env_path, self.args.threads, self.args.restart)
  File "/public/tools/EVG/src/convert.py", line 73, in bgzip_vcf
    stdout, stderr, log_out = run_cmd.run(cmd, env_path)
  File "/public/tools/EVG/src/run_cmd.py", line 57, in run
    stdout = stdout_data.strip().decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by unavailable-2374** [comment]
And graphvcf gets a Segmentation fault (core dumped) halfway through the run.

**Comment by duzezhen** [comment]
Thank you for your feedback. It's possible that the issue lies with the VCF file format. Could you please provide us with your VCF files and the reference genome to resolve this issue? A subset of the VCF files, such as chromosome 1 or the first 1000 lines, would suffice. Of course, assuming this subset exhibits the issue you mentioned.

If it's convenient for you, you can send them to our email or share them with us via a cloud storage service. Looking forward to your response.

**Comment by unavailable-2374** [comment]
Thank you for your quickly reply.

This is my VCF file which processed by PGGB, I made a little change on GT, put 0 to 0/0; 1 to 1/1.

Wish it be helpful~

Best,
Shuo
￼

**Comment by unavailable-2374** [comment]
This demo seems like no problem, but when I run "graphvcf convert -r convert/convert.ref.fa -v 1.cook.vcf.gz -l 350 -o convert.1.cooked.vcf” it will stop at 2418112, and report: Aborted (core dumped).

I can’t figure out, if you got any advice please let me know.

Best,
Shuo

**Comment by duzezhen** [comment]
Since we don't have your variant file, we can't directly pinpoint the error. If you're certain that the downstream genotyping software can use the provided VCF file, you can unzip the original file and copy it to the "convert" folder like this:

`zcat /public/genome/output/VCF/1.cooked.vcf.gz > public/genome/output/VCF/convert/convert.1.cooked.vcf`

Make sure the filename is "convert.1.cooked.vcf". Then run EVG with the "--restart" parameter, and it will automatically skip the VCF conversion step.

After that, we'll use other datasets based on PGGB to identify variants and pinpoint the exact issue. Alternatively, you can split the VCF file and run graphvcf convert to identify which line has the formatting error.

**Comment by unavailable-2374** [comment]
Thanks for the reply!

If you have any progress on deal genotyping when using the result comes from PGGB please let me know, I still got a lot of problems on that.

Best~

**Comment by duzezhen** [comment]
Sorry for getting back to you so late!

We identified variants from four Arabidopsis genomes using `pggb`, and successfully converted them using `graphvcf convert`. Therefore, we are still unable to pinpoint the issue with your file.
